server:
  ssl:
    key-store: ${SMARTMETER_KEYSTORE_LOCATION}
    key-store-password: ${SMARTMETER_KEYSTORE_PASSWORD}
    key-store-type: JKS
    trust-store: ${SMARTMETER_TRUSTSTORE_LOCATION}
    trust-store-password: ${SMARTMETER_TRUSTSTORE_PASSWORD}
    trust-store-type: JKS

spring:
  application:
    name: smartmeter
  rabbitmq:
    host: ${SMARTMETER_RABBITMQ_HOST}
    port: 5672
    username: ${SMARTMETER_RABBITMQ_USERNAME}
    password: ${SMARTMETER_RABBITMQ_PASSWORD}