spring:
  profiles:
    active: local
  application:
    name: smart-meter
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        show_sql: true
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      data-source-properties:
        oracle:
          net:
            CONNECT_TIMEOUT: 10000
            READ_TIMEOUT: 10000
          jdbc:
            ReadTimeout: 10000
  amqp:
    deserialization:
      trust:
        all: true

---
spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret
---
spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: 165.227.225.78
    port: 5672
    username: xxx
    password: xxx