server:
  ssl:
    key-store: ${SMARTMETER_KEY_STORE_LOCATION}
    key-store-password: ${SMARTMETER_KEY_STORE_PASSWORD}
    key-alias: ${SMARTMETER_KEY_STORE_ALIAS}

spring:
  application:
    name: smart-meter
  rabbitmq:
    host: ${SMARTMETER_RABBITMQ_HOST}
    port: 5672
    username: ${SMARTMETER_RABBITMQ_USERNAME}
    password: ${SMARTMETER_RABBITMQ_PASSWORD}